config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # get 'cards/index'
  get "main" => "cards#index"
  post "new_card" => "cards#create"
  root 'cards#index'

  resources :cards
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
    # desc:text date:text member:text list:text

end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
    def index
        puts "UUTTTTTTTTTTTTTT
        @@@@@@"
        @all_cards = Card.all
    end

    def show
    end

    def create
        # @cards = Card.all
        newest_card = Card.new(user_params)
        newest_card.save
        redirect_to '/''
    end

    def user_params
        params.require(:card).permit(:title, :desc, :date, :member, :list)
      end
  end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user, :list)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/cards/card.html.erb
<h1>THIS IS A CARD</h1>

app/views/cards/index.html.erb
<div class="container">
<table> 
  <% @all_cards.each do |card| %>
    <tr>
      <td><%= card.title %></td>
      <td><%= card.desc %></td>
      <td><%= card.date %></td>
      <td><%= card.member %></td>
      <td><%= card.member %></td>
    </tr>
  <% end %>
</table>
  <div class="list">
      <%= form_with scope: :card, url: new_card_path, local: true do |form| %>
      <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
      </p>
    
      <p>
        <%= form.label :desc %><br>
        <%= form.text_field :desc %>
      </p>
      
      <p>
        <%= form.label :date %><br>
        <%= form.text_field :date %>
      </p>
      
      <p>
        <%= form.label :member%><br>
        <%= form.text_field :member %>
      </p>
      
      <p>
        <%= form.label :list %><br>
        <%= form.text_field :list %>
      </p>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
      <p>
        <%= form.submit %>
      </p>
  <% end %>
  </div>
   
  <div class="list">
          <%= form_with scope: :card, url: new_card_path, local: true do |form| %>
      <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
      </p>
    
      <p>
        <%= form.label :desc %><br>
        <%= form.text_field :desc %>
      </p>
      
      <p>
        <%= form.label :date %><br>
        <%= form.text_field :date %>
      </p>
      
      <p>
        <%= form.label :member%><br>
        <%= form.text_field :member %>
      </p>
      
      <p>
        <%= form.label :list %><br>
        <%= form.text_field :list %>
      </p>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
      <p>
        <%= form.submit %>
      </p>
    <% end %>
  </div>
   
  <div class="list">
          <%= form_with scope: :card, url: new_card_path, local: true do |form| %>
      <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
      </p>
    
      <p>
        <%= form.label :desc %><br>
        <%= form.text_field :desc %>
      </p>
      
      <p>
        <%= form.label :date %><br>
        <%= form.text_field :date %>
      </p>
      
      <p>
        <%= form.label :member%><br>
        <%= form.text_field :member %>
      </p>
      
      <p>
        <%= form.label :list %><br>
        <%= form.text_field :list %>
      </p>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
      <p>
        <%= form.submit %>
      </p>
    <% end %>
  </div>
</div>





<style>
.list {
    border: 2px solid black;
}
.container {
    display: flex;
}
</style>





        <%# <form method="post" action="new_card">
        <p><label>TITLE</label></p>
        <input type="text" name="title"></input>
        <p><label>DESCRIPTION</label></p>
        <input type="text" name="desc"></input>
        <p><label>DATE</label></p>
        <input type="text" name="date"></input>
        <p><label>MEMBER</label></p>
        <input type="text" name="member"></input>
        <p><label>LIST</label></p>
        <input type="text" name="list"></input>
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>
        <%# <button type="submit">SUBMIT</button> %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trillo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :user %>
    <%= form.text_area :user %>
  </div>

  <div class="field">
    <%= form.label :list %>
    <%= form.text_area :list %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th>List</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.user %></td>
        <td><%= post.list %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user %>
</p>

<p>
  <strong>List:</strong>
  <%= @post.list %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>